parameters:


    env(DATABASE URL): ''


doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: ut8mb4_unicode_ci

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
    #dql:
        #numeric_functions:
            #ASIN: DoctrineExtensions\Query\Mysql\Asin
            #POWER: DoctrineExtensions\Query\Mysql\Power
            #SIN: DoctrineExtensions\Query\Mysql\Sin
            #PI: DoctrineExtensions\Query\Mysql\Pi
            #COS: DoctrineExtensions\Query\Mysql\Cos